"""Add course_completions table

Revision ID: 06faf44b6775
Revises: f6d2c0d0ce74
Create Date: 2025-09-23 18:29:18.113401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06faf44b6775'
down_revision = 'f6d2c0d0ce74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_user_course_completion')
    )
    with op.batch_alter_table('course_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_completions_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_completions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('color')

    with op.batch_alter_table('course_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_completions_user_id'))
        batch_op.drop_index(batch_op.f('ix_course_completions_course_id'))

    op.drop_table('course_completions')
    # ### end Alembic commands ###
