"""Add profile/theming fields to users

Revision ID: 3366426ed5bf
Revises: 06faf44b6775
Create Date: 2025-09-23 21:28:48.071434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3366426ed5bf'
down_revision = '06faf44b6775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
