"""Add monetization fields to courses

Revision ID: 9af3901c237a
Revises: 3366426ed5bf
Create Date: 2026-01-02 20:27:49.550635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text



# revision identifiers, used by Alembic.
revision = '9af3901c237a'
down_revision = '3366426ed5bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('creator_payout_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('stripe_account_id', sa.String(length=120), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('details_submitted', sa.Boolean(), nullable=True),
    sa.Column('charges_enabled', sa.Boolean(), nullable=True),
    sa.Column('payouts_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator_payout_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_payout_accounts_creator_id'), ['creator_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_creator_payout_accounts_stripe_account_id'), ['stripe_account_id'], unique=True)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_stripe_checkout_session_id'), ['stripe_checkout_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_stripe_payment_intent_id'), ['stripe_payment_intent_id'], unique=False)

    op.create_table('platform_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Integer(), nullable=False),
    sa.Column('platform_fee_amount', sa.Integer(), nullable=False),
    sa.Column('creator_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refund_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('stripe_charge_id', sa.String(length=120), nullable=True),
    sa.Column('stripe_refund_id', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_refund_id')
    )
    with op.batch_alter_table('refund_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refund_logs_stripe_charge_id'), ['stripe_charge_id'], unique=False)

    op.create_table('transfer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('stripe_transfer_id', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('course_students')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=False, server_default=text("0")))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=False, server_default=text("'usd'")))
        batch_op.add_column(sa.Column('price_cents', sa.Integer(), nullable=False, server_default=text("0")))
        batch_op.add_column(sa.Column('revenue_share_pct', sa.Numeric(precision=5, scale=4), nullable=False, server_default=text("0.8800")))
        batch_op.add_column(sa.Column('stripe_product_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=120), nullable=True))

        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_product_id')
        batch_op.drop_column('revenue_share_pct')
        batch_op.drop_column('price_cents')
        batch_op.drop_column('currency')
        batch_op.drop_column('is_paid')

    op.create_table('course_students',
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'student_id')
    )
    op.drop_table('transfer_logs')
    with op.batch_alter_table('refund_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refund_logs_stripe_charge_id'))

    op.drop_table('refund_logs')
    op.drop_table('order_items')
    op.drop_table('platform_customers')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_stripe_payment_intent_id'))
        batch_op.drop_index(batch_op.f('ix_orders_stripe_checkout_session_id'))
        batch_op.drop_index(batch_op.f('ix_orders_buyer_id'))

    op.drop_table('orders')
    with op.batch_alter_table('creator_payout_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_payout_accounts_stripe_account_id'))
        batch_op.drop_index(batch_op.f('ix_creator_payout_accounts_creator_id'))

    op.drop_table('creator_payout_accounts')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
